apiVersion: v1
kind: Secret
metadata:
  name: circleguard-auth-secret
  namespace: circleguard-dev
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_LDAP_PASSWORD: admin
  JWT_SECRET: my-super-secret-dev-key-32-chars-long-12345678
  QR_SECRET: my-qr-secret-key-for-dev-1234567890
