apiVersion: v1
kind: ConfigMap
metadata:
  name: circleguard-identity-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/circleguard_identity
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SERVER_PORT: "8083"
