apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-identity
  namespace: circleguard-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-identity
  template:
    metadata:
      labels:
        app: circleguard-identity
    spec:
      containers:
        - name: circleguard-identity
          image: localhost:5000/circleguard/identity-service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: circleguard-identity-config
            - secretRef:
                name: circleguard-identity-secret
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
