apiVersion: v1
kind: Secret
metadata:
  name: circleguard-promotion-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_NEO4J_AUTHENTICATION_PASSWORD: password
  JWT_SECRET: my-super-secret-dev-key-32-chars-long-12345678
